label: Grouping
columns:
  - width: 1/2
    fields:
      entriesheading:
        label: Entries - Repeatable fields
        type: headline
      entriestext:
        type: entries
        label: Texts
        field:
          type: text
      entriescolor:
        type: entries
        label: Colors
        field:
          type: color
          options:
            "#F8B195": "Sunny rays"
            "#F67280": "First-love blush"
            "#C06C84": "Cherry blossom"
            "#6C5B7B": "Morning gloom"
            "#355C7D": "Midnight rain"
      entriesdates:
        type: entries
        label: Dates
        width: 1/2
        field:
          type: date
      entries:
        type: entries
        label: Selects
        width: 1/2
        min: 2
        max: 4
        required: true
        help: "min:2, max: 4"
        field:
          type: select
          options:
            design: Design
            architecture: Architecture
            photography: Photography
            3d: 3D
            web: Web
  - width: 1/2
    fields:
      groupheading:
        label: Field Group
        type: headline
      group: fields/meta

